spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercadolivro
    username: root
    password:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
